[package]
name = "xtask"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
xflags = "0.2.4"
xshell = "0.2.1"
